num1=int(input("Enter the First Number  :  "))
num2=int(input("Enter the Second Number  :  "))
print("num1 & num2 = ",num1&num2)
print("num1 | num2 = ",num1|num2)
print("num1 ^ num2 = ",num1^num2)
input()
