num1=int(input("Enter the First Number :  "))
num2=int(input("Enter the Second Numbet:  "))
print("Num1 is < num2 : ",num1<num2)
print("Num1 is <= num2 : ",num1<=num2)
print("Num1 is > num2 : ",num1>num2)
print("Num1 is >= num2 : ",num1>=num2)
print("Num1 is == num2 : ",num1==num2)
print("Num1 is != num2 : ",num1 =num2)
input()
